Author: Nishita Raghavendra

## Task A - Matrix Generation

In [1]:
import numpy as np

np.random.seed(42)

A = np.random.randint(1, 11, size=(4, 3))
B = np.random.randint(1, 11, size=(3, 5))

print("Matrix A", A.shape)
print(A)
print()
print("Matrix B", B.shape)
print(B)

Matrix A (4, 3)
[[ 7  4  8]
 [ 5  7 10]
 [ 3  7  8]
 [ 5  4  8]]

Matrix B (3, 5)
[[ 8  3  6  5  2]
 [ 8  6  2  5  1]
 [10  6  9  1 10]]


## Task B - Dimension Validation & Dot Product

In [2]:
# inner dims have to match for the dot product to even be defined
assert A.shape[1] == B.shape[0]

C = A.dot(B)

print("Matrix C", C.shape)
print(C)
assert C.shape == (4, 5)

Matrix C (4, 5)
[[168  93 122  63  98]
 [196 117 134  70 117]
 [160  99 104  58  93]
 [152  87 110  53  94]]


## Task C - Reductions & Summary Statistics

In [3]:
total = C.sum()
row_sums = C.sum(axis=1)
col_sums = C.sum(axis=0)

print("Total sum:", total)
print("Row sums:", row_sums)
print("Column sums:", col_sums)

Total sum: 2188
Row sums: [544 634 514 496]
Column sums: [676 396 470 244 402]
